mblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from posts.views import PostSitemap, StaticViewSitemap

sitemaps = {
    'posts': PostSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^api/posts/', include("posts.api.urls", namespace='posts-api')),
    url(r'^', include("posts.urls")),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url

from .views import (PostListAPIView, PostDetailAPIView, PostUpdateAPIView, PostDeleteAPIView, PostCreateAPIView)

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name="list"),
    url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
    # url(r'^contacts/$', contacts, name="contacts"),
    # url(r'^login/$', user_login, name='login'),
    # url(r'^logout/$', user_logout, name='logout'),
    # url(r'^like/$', like_post, name='like_post'),
    url(r'^(?P<id>[-\w]+)/$', PostDetailAPIView.as_view(), name="detail"),
    url(r'^(?P<slug>[-\w]+)/up/$', PostUpdateAPIView.as_view(), name="update"),
    url(r'^(?P<slug>[-\w]+)/del/$', PostDeleteAPIView.as_view(), name="delete"),
    # url(r'^(?P<slug>[-\w]+)/$', show_category, name='show_category'),

]

posts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import (post_list, post_create, post_detail, post_update, post_delete, show_category, contacts, register,
                    user_login, user_logout, like_post, user_page, change_password, user_change, contact_form)

urlpatterns = [
    url(r'^$', post_list, name="list"),
    url(r'^contact-form/$', contact_form),
    url(r'^create/$', post_create, name="create"),
    url(r'^contacts/$', contacts, name="contacts"),
    url(r'^registration/$', register, name="regist"),
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^like/$', like_post, name='like_post'),
    url(r'^user/$', user_page, name='user_page'),
    url(r'^user/pw-change/$', change_password, name='change_password'),
    url(r'^user/user-change/$', user_change, name='user_change'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$', post_detail, name="detail"),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/up/$', post_update, name="update"),
    url(r'^(?P<category>[-\w]+)/(?P<slug>[-\w]+)/del/$', post_delete, name="delete"),
    url(r'^(?P<slug>[-\w]+)/$', show_category, name='show_category'),

]

posts/models.py
### -*- coding: utf-8 -*- ###
from __future__ import unicode_literals
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from redactor.fields import RedactorField
from mptt.models import MPTTModel, TreeForeignKey
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True, verbose_name='Название')
    slug = models.SlugField(unique=True)
    image = models.ImageField(blank=True, verbose_name='Изображение')

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'

    # For Python 2, use __unicode__ too
    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('show_category', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        try:
            this_record = Category.objects.get(id=self.id)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(Category, self).save(*args, **kwargs)


class Post(models.Model):
    category = models.ForeignKey(Category, default=1, verbose_name='Категория')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, verbose_name='Пользователь')
    title = models.CharField(max_length=120, verbose_name='Заголовок')
    slug = models.SlugField(unique=True)
    image = models.ImageField(blank=True, verbose_name='Изображение')
    content = RedactorField(max_length=10000, verbose_name='Контент')
    timestamp = models.DateTimeField(verbose_name='Дата')
    keywords = models.CharField(max_length=1024, blank=True)
    description = models.CharField(max_length=1024, blank=True)
    likes = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Статьи'
        verbose_name_plural = 'Статьи'
        ordering = ["-timestamp"]

    # For Python 2, use __unicode__ too
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug': self.slug, 'category': self.category})

    def save(self, *args, **kwargs):
        try:
            this_record = Post.objects.get(id=self.id)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(Post, self).save(*args, **kwargs)


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        try:
            this_record = UserProfile.objects.get(id=self.id)
            if this_record.picture != self.picture:
                this_record.picture.delete(save=False)
        except:
            pass
        super(UserProfile, self).save(*args, **kwargs)


class Comment(MPTTModel):
    post = models.ForeignKey(Post)
    date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    content = models.TextField(max_length=250, unique=True)
    moderation = models.BooleanField(default=False)

    class MPTTMeta:
        order_insertion_by = ['date']

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

posts/api/views.py
from django.db.models import Q
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.generics import (ListAPIView, RetrieveAPIView, UpdateAPIView, DestroyAPIView, CreateAPIView,
                                     RetrieveUpdateAPIView)
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAdminUser, IsAuthenticatedOrReadOnly

from posts.models import Post
from .serializers import PostSerializer, PostCreateSerializer, PostListSerializer
from .pagination import PostPageNumberPagination


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer
    permission_classes = [IsAuthenticated]

    def per_create(self, serializer):
        serializer.save(user=self.request.user)


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    lookup_field = 'id'


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateSerializer
    lookup_field = 'slug'
    permission_classes = [IsAuthenticated]

    def per_update(self, serializer):
        serializer.save(user=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    lookup_field = 'slug'
    permission_classes = [IsAdminUser]


class PostListAPIView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ('title', 'content')
    pagination_class = PostPageNumberPagination

templates/account.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{{ user }} | {{block.super}}{% endblock title %}
{% block extra_body %}
    <script type="text/javascript">
$(document).ready(function() {
    $('body').addClass('login-page');
    $('nav').removeClass('navbar-default navbar-fixed-top navbar-color-on-scroll navbar-transparent');
    $('nav').addClass('navbar-primary navbar-transparent navbar-absolute');
});
</script>
{% endblock %}
{%block content%}
<div class="page-header header-filter" filter-color="blue">
    <div class="hero" id="particles-js">
		<div class="container">
        {% include "messages.html" %}
			<div class="row">
    			<div class="col-md-10 col-md-offset-1">

					<div class="card card-profile">
                        <div class="card-avatar">
                            {% if user.socialaccount_set.all.0.get_avatar_url %}
                                <a href=""><img class="img" alt="{{ user }}" src="{{ user.socialaccount_set.all.0.get_avatar_url }}"></a>
                            {% elif user.userprofile.picture %}
                                 <a href=""><img class="img" alt="{{ user }}" src="{{ user.userprofile.picture.url }}"></a>
                            {% else %}
                                <a href=""><img class="img" alt="{{ user }}" src="{% static "/img/standart.jpg" %}"></a>
                            {% endif %}
                        </div>
                        <h2 class="card-title text-center">{{ user }}{% if user.is_superuser %} (admin){% endif %}</h2>
                        <div class="row">
                            {% if user.socialaccount_set.all.0.get_avatar_url %}
                            <div class="col-md-5 col-md-offset-1">
            					<div class="info info-horizontal" style="max-width: 90%;">
                                    <div class="icon icon-info">
            							<i class="material-icons">verified_user</i>
            						</div>
            						<div class="description">
                                        <h4 class="info-title"><a href="{% url 'change_password' %}">Смена пароля</a></h4>
                                    </div>
                                    <div class="icon icon-info">
            							<i class="material-icons">account_circle</i>
            						</div>
            						<div class="description">
                                        <h4 class="info-title"><a href="{% url 'user_change' %}">Смена имени</a></h4>
                                    </div>
                                </div>

            				</div>
                            {% else %}
                                <div class="col-md-5 col-md-offset-1">
            					<div class="info info-horizontal" style="max-width: 90%;">
            						<div class="icon icon-info">
            							<i class="material-icons">perm_media</i>
            						</div>
            						<div class="description">
            							<h4 class="info-title">Изображение профиля</h4>
                                        <form method="post" action=" " enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="checkbox">
								            <label><input type="checkbox" name="picture-clear" id="picture-clear_id">Очистить</label>
							                </div>
                                            <div class="form-group form-file-upload is-empty is-fileinput">
                                                <input type="file" name="picture" id="id_picture">
                                                <div class="input-group">
                                                    <span class="input-group-addon"><i class="material-icons">camera</i></span>
                                                    <input type="text" readonly="" class="form-control" placeholder="Фото">
                                                </div>
                                                <span class="material-input"></span></div>
                                            <input type="submit" value="Изменить" class="btn btn-primary" >
                                        </form>
                                    </div>
                                </div>
            				</div>
                            <div class="col-md-5 col-md-offset-1">
            					<div class="info info-horizontal" style="max-width: 90%;">
                                    <div class="icon icon-info">
            							<i class="material-icons">verified_user</i>
            						</div>
            						<div class="description">
                                        <h4 class="info-title"><a href="{% url 'change_password' %}">Смена пароля</a></h4>
                                    </div>
                                    <div class="icon icon-info">
            							<i class="material-icons">account_circle</i>
            						</div>
            						<div class="description">
                                        <h4 class="info-title"><a href="{% url 'user_change' %}">Смена имени</a></h4>
                                    </div>
                                </div>
            				</div>
                            {% endif %}

                        </div>
                	</div>

                </div>
            </div>
		</div>
        <div class="w wave"></div>
        <div class="w wave2"></div>
        <div class="w wave3"></div>
        <div class="w wave4"></div>
    </div>
</div>
{%endblock content%}

templates/base.html
{% load staticfiles %}
{% load recaptcha2 %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
	<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="theme-color" content="#1f2fa2">
	<title>{%block title%}Useful Me{%endblock title%}</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    {% include "meta.html" %}
	<!--     Fonts and icons     -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
	<!-- CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/material-kit.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/wave.css' %}" rel="stylesheet"/>
    {% block extra_css %}{% endblock %}
    {% recaptcha_init %}
    <meta name="google-site-verification" content="CdmL3H2c4Foj6OkVwoPhwO693lmmw6H_hypJI-TcPf4" />
    <!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter41690929 = new Ya.Metrika({ id:41690929, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/41690929" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
</head>
<body>
{% include "nav.html" %}
{% block content %}{%endblock content %}
</body>
<!--   Core JS Files   -->
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-99062518-1', 'auto');
  ga('send', 'pageview');
    </script>
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/material.min.js' %}"></script>
	<!--	Plugin for Select Form control, full documentation here: https://github.com/FezVrasta/dropdown.js -->
	<script src="{% static 'js/jquery.dropdown.js' %}" type="text/javascript"></script>
	<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
	<script src="{% static 'js/material-kit.js' %}" type="text/javascript"></script>
{% block extra_body %}{% endblock %}
</html>

templates/contact.html
{% extends "base.html" %}
{% block title %}Контакты | {{block.super}}{% endblock title %}
{% block extra_body %}
    <script type="text/javascript">$('body').addClass('contact-page');</script>
{% endblock %}
{%block content%}
<div class="page-header header-filter header-small" data-parallax="active" style="background-image: linear-gradient(60deg, #00bcd4, #1f2fa2);">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <h1 class="title">Контакты</h1>
            </div>
        </div>
    </div>
</div>
<div class="main main-raised">
    <div class="contact-content">
        <div class="container">
            {% include "messages.html" %}
            <h2 class="title">Отправьте сообщение</h2>
            <div class="row">
                <div class="col-md-12">
                    <p class="description">Контактная форма для связи со мной. Все поля обязательны кроме Темы письма.<br><br></p>
                    <form role="form" id="contact-form" method="post" action=" ">{% csrf_token %}
                    {{ form.non_field_errors }}
                        <div class="form-group label-floating is-empty">
                            <label for="{{ form.subject.id_for_label }}" class="control-label">Тема</label>
                            <input id="id_subject" type="text" name="subject" class="form-control">
							<span class="material-input" style="color: #f44336;">{{ form.subject.errors }}</span>
                        </div>
                        <div class="form-group label-floating is-empty">
                            <label for="{{ form.name.id_for_label }}" class="control-label">Ваше имя</label>
                            <input id="id_name" type="text" name="name" class="form-control">
							<span class="material-input" style="color: #f44336;">{{ form.name.errors }}</span>
                        </div>
                        <div class="form-group label-floating is-empty">
                            <label for="{{ form.sender.id_for_label }}" class="control-label">Email адрес</label>
                            <input id="id_sender" type="email" name="sender" class="form-control">
							<span class="material-input" style="color: #f44336;">{{ form.sender.errors }}</span>
                        </div>
                        <div class="form-group label-floating is-empty">
                            <label for="{{ form.message.id_for_label }}" class="control-label">Сообщение</label>
                            <textarea id="id_message" type="text" name="message" class="form-control" rows="6"></textarea>
							<span class="material-input" style="color: #f44336;">{{ form.message.errors }}</span>
                        </div>
                        <div class="form-group label-floating is-empty">
                            {{ form.captcha }}
							<span class="material-input" style="color: #f44336;">{{ form.captcha.errors }}</span>
                        </div>
                        <div class="submit text-center">
                            <input type="submit" class="btn btn-info btn-raised btn-round" value="Отправить">
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
    {% include "footer.html" %}
{%endblock content%}

templates/footer.html
<footer class="footer">
    <div class="container">
        <a class="footer-brand" href="{% url 'list' %}">Useful Me</a>
        <ul class="pull-center">
            <li><a href="{% url 'contacts' %}">Контакты</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'user_page' %}">Вы( {{ user.username }} )</a></li>
                <li><a href="{% url 'logout' %}">Выход</a></li>
            {% else %}
                <li><a href="{% url 'regist' %}">Регистрация</a></li>
                <li><a href="{% url 'login' %}">Войти</a></li>
            {% endif %}
        </ul>
        <ul class="social-buttons pull-right">
            <li>
                <a href="https://vk.com/id41553847" target="_blank" class="btn btn-just-icon btn-vk btn-simple"><i class="fa fa-vk"></i>
                </a>
            </li>
            <li>
                <a href="https://github.com/Vitalio44" target="_blank" class="btn btn-just-icon btn-github btn-simple"><i class="fa fa-github"></i></a>
            </li>
        </ul>
    </div>
</footer>

templates/meta.html
<meta name="author" content="{{ instance.user }}" />
<meta name="keywords" content="{{ instance.keywords }}" />
<meta name="description" content="{{ instance.description }}" />

templates/post_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load mptt_tags %}
{% block title %}{{instance.title}} | {{block.super}}{% endblock title %}
{% block extra_body %}
    <script>
        $('#likes').click(function(){
            var postid;
            postid = $(this).attr("data-postid");
            $.get('/like/', {obj_id: postid}, function(data){
                $('#like_count').html(data);
            });
        });
    </script>
{% endblock %}
{%block content%}
<div class="page-header header-filter header-small" data-parallax="active"
        {% if instance.image %} style="background-image: url('{{ instance.image.url }}');"
     {% else %}style="background-image: linear-gradient(60deg, #00bcd4, #1f2fa2);"{% endif %}>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <h1 class="title">{{ title }}</h1>
            </div>
        </div>
    </div>
</div>
<div class="main main-raised">
    <div class="container">
    {% include "messages.html" %}
        <div class="section section-text">
            <div class="row">
                <div class="col-md-7 col-md-offset-1">
                        <h3 class="title">{{ title }}</h3>
                        {% autoescape off %}{{ instance.content }}{% endautoescape %}
                        <hr>
                        <div>
                        <a id="likes" data-postid="{{ instance.id }}" class="btn btn-danger btn-simple pull-right">
                            <i class="material-icons">favorite</i> <span id="like_count">{{ instance.likes }}</span><div class="ripple-container"></div>
                        </a>
                        </div>
                    </div>
                <div class="col-md-2 col-md-offset-1 stats">
                    <h4 class="title">Автор</h4>
                    <ul class="list-unstyled">
                        <li><b>{{ instance.user }}</b></li>
                    </ul>
                    <hr />
                    <h4 class="title">Расскажи</h4>
                    <a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}" class="btn btn-twitter btn-round">
                        <i class="fa fa-twitter"></i> Twitter</a>
                    <a href="http://vk.com/share.php?url={{ request.build_absolute_uri }}" class="btn btn-vk btn-round">
                        <i class="fa fa-vk"></i> ВКонтакте</a>
                    <a href="https://www.facebook.com/sharer.php?u={{ request.build_absolute_uri }}" class="btn btn-facebook btn-round">
                        <i class="fa fa-facebook-square"></i> Facebook</a>
                    <a href="https://plus.google.com/share?url={{ request.build_absolute_uri }}" class="btn btn-google btn-round">
                        <i class="fa fa-google-plus"></i> Google</a>
                    <hr />
                </div>
            </div>
        </div>
        <div class="section section-comments">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
                    {% if nodes %}
						<div class="media-area">
							<h3 class="title text-center">Комментарии ({{ nodes.count }})</h3>
                            {% recursetree nodes %}
							<div class="media">
                                <a class="pull-left" >
                                    <div class="avatar">
                                        {% if node.user.socialaccount_set.all.0.get_avatar_url %}
                                             <img class="media-object" alt="{{ node.user }}" src="{{ node.user.socialaccount_set.all.0.get_avatar_url }}">
                                        {% elif node.user.userprofile.picture %}
                                            <img class="media-object" alt="{{ node.user }}" src="{{ node.user.userprofile.picture.url }}">
                                        {% else %}
                                            <img class="media-object" alt="{{ node.user }}" src="{% static "/img/standart.jpg" %}">
                                        {% endif %}
                                    </div>
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading">{{ node.user }} <small>· {{ node.date|timesince }}</small></h4>
                                    <p>{{ node.content }}</p>
                                    <div class="media-footer">
                                        {% if not node.parent %}
                                            {% if user.is_authenticated %}
                                            <div class="panel panel-default">
                                                <div class="panel-heading" role="tab" id="headingOne">
                                                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne{{ node.id }}" aria-expanded="false" aria-controls="collapseOne" class="collapsed">
                                                        <h4 class="panel-title">Ответить<i class="material-icons">keyboard_arrow_down</i></h4>
                                                    </a>
                                                </div>
                                                <div id="collapseOne{{ node.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" aria-expanded="false" style="height: 0px;">
                                                    <div class="panel-body">
                                                        <div class="media-body">
                                                            <form method="POST" action=" ">
                                                                <div class="form-group is-empty">
                                                                    {% csrf_token %}
                                                                    <input type="hidden" name="parent" value="{{ node.id }}">
                                                                    <textarea name="content" rows="6" class="form-control" placeholder="Ответ на комментарий выше" maxlength="250" required="" id="id_content"></textarea>
                                                                    <span class="material-input"></span>
                                                                </div>
                                                                <div class="media-footer"><input type="submit" class="btn btn-primary btn-round btn-wd pull-right" value="Отправить"></div>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                    {% if not node.is_leaf_node %}
                                        {{ children }}
                                    {% endif %}
                                </div>
							</div>
                            {% endrecursetree %}
						</div>
                    {% endif %}
                    {% if user.is_authenticated %}
						  <h3 class="title text-center">Твой комментарий</h3>
						  <div class="media media-post">
                              {% if user.userprofile.picture %}
							  <a class="pull-left author" href="/">
								  <div class="avatar">
										<img class="media-object" alt="{{ user }}" src="{{ user.userprofile.picture.url }}">
								  </div>
							  </a>
                              {% else %}
                                  <a class="pull-left author" href="/">
								  <div class="avatar">
										<img class="media-object" alt="{{ user }}" src="{% static "/img/standart.jpg" %}">
								  </div>
							  </a>
                              {% endif %}
							  <div class="media-body">
                                  <form method="POST" action=" ">
                                      <div class="form-group is-empty">
                                          {% csrf_token %}
                                          <textarea name="content" rows="6" class="form-control" placeholder="Напиши хороший комментарий или ничего..." maxlength="250" required="" id="id_content"></textarea>
                                          <span class="material-input"></span>
                                      </div>
                                      <div class="media-footer">
                                          <input type="submit" class="btn btn-primary btn-round btn-wd pull-right" value="Отправить">
                                      </div>
                                  </form>
							  </div>
						  </div> <!-- end media-post -->
                    {% else %}
                        <h3 class="title text-center">
                            <a class="text-primary" href="{% url 'account_signup' %}">Зарегистрируйтесь</a> или
                            <a class="text-primary" href="{% url 'account_login' %}">авторизируйтесь</a> для комментирования
                        </h3>
                    {% endif %}
					</div>
				</div>
			</div>
    </div>
</div>
    {% include "footer.html" %}
{%endblock content%}